apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nodejs-server-autoscaler
  namespace: riadkolli
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodejs-server
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50