
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-server
  namespace: riadkolli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-server
  template:
    metadata:
      labels:
        app: nodejs-server
    spec:
      containers:
        - name: nodejs-server
          image: riko99/riad:latest
          env:
            - name: RABBITMQ_URL
              value: "amqp://162.19.110.149:5672"
            - name: PGHOST
              value: "postgres"
            - name: PGPORT
              value: "5432"      
            - name: PGUSER
              value: "myuser"
            - name: PGDATABASE
              value: "mydatabase"
            - name: PGPASSWORD
              value: "mypassword"        
            - name: PORT
              value: "5432"                           

          ports:
            - containerPort: 4040

---

apiVersion: v1
kind: Service
metadata:
  name: nodejs-server-service
  namespace: ddjordjevic
spec:
  selector:
    app: nodejs-server
  ports:
    - protocol: TCP
      port: 4040
      targetPort: 4040
  type: LoadBalancer
